# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '/'
    weight: 10
  - name: Tutorials
    weight: 20
    identifier: tutorials
  - name: Hidden Markov Models
    weight: 10
    PageRef: course/hidden-markov-models
    parent: tutorials
  # - name: Data science
  #   PageRef: course/data-science/_index.md
  #   weight: 10
  #   parent: courses
  # - name: Robotics
  #   PageRef: course/robotics/_index.md
  #   weight: 20
  #   parent: courses
  - name: Blog
    PageRef: post/_index.md
    weight: 30
  - name: Contact
    PageRef: contact/index.md
    weight: 60
